all_file_name: data/clean_anno.json # after jy's dataset path change
train_file_name: data/train  
val_file_name: data/val_data.json
test_file_name: data/test_data.jaon
batch_size: 8
num_epoch: 10
wandb: False
name: small_pool_ # wandb run name, model save folder name
model_path: 'facebook/dpr-question_encoder-single-nq-base' # model/ep4_acc0.769
tokenizer_path: "data/tokenizer/tokenizer-bpe.json"
num_neg: 1
learning_rate: !!float 2e-5
adam_epsilon: !!float 1e-08
gradient_accumulation_steps: 1
warmup_steps: 0
weight_decay: 0.01

# fixed parameter
seed: 1004
report_step: 1
max_length_token: 100
vocab_size: 600
hidden_size: 384