file_name: data/anno.json # after jy's dataset path change
batch_size: 1
num_epoch: 5
wandb: False
name: ex # wandb run name, model save folder name
model_path:  'facebook/dpr-question_encoder-single-nq-base' # user's pretrained weight or hugginface model name
tokenizer_path: "data/tokenizer-wordlevel.json"
num_neg: 2
learning_rate: !!float 2e-5
adam_epsilon: !!float 1e-08
gradient_accumulation_steps: 1
warmup_steps: 0
weight_decay: 0.01

# fixed parameter
seed: 1004
report_step: 100
max_length_token: 100
vocab_size: 600